### ISSUE TITLE
`forum.snapcraft.io` is 503 and `status.snapcraft.io` doesn't report it.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [canonical-webteam/snapcraft-email-comms#7]
Not unpredictable. However, https://status.snapcraft.io/ doesn't report any failures. I've been unable to locate where to report this, so I'm reporting it here.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/canonical/snapcraft-email-comms/issues/7#issue-2240413064

It's accessible again. I can post about this at the forum itself.
